# 🚀 Release Drafter Configuration
# 自動生成 release notes，基於 PR 標籤分類變更

name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"

# 📋 變更分類
categories:
  - title: "💥 Breaking Changes"
    collapse-after: 5
    labels:
      - "breaking"

  - title: "✨ Features"
    collapse-after: 10
    labels:
      - "feature"

  - title: "🐛 Bug Fixes"
    collapse-after: 10
    labels:
      - "bugfix"

  - title: "🧰 Maintenance"
    collapse-after: 3
    labels:
      - "chore"

  - title: "📦 Dependencies"
    collapse-after: 3
    labels:
      - "dependencies"

  - title: "📝 Documentation"
    collapse-after: 3
    labels:
      - "documentation"

  - title: "🧪 Tests"
    collapse-after: 5
    labels:
      - "unit-test"

  - title: "⚡️ Performance Improvements"
    collapse-after: 5
    labels:
      - "perf"

  - title: "🔒️ Security Fixes"
    collapse-after: 3
    labels:
      - "security"

  - title: "♻️ Code Refactoring"
    collapse-after: 5
    labels:
      - "refactor"

  - title: "🎨 Code Style & Formatting"
    collapse-after: 5
    labels:
      - "style"

  - title: "🔙 Reverts"
    collapse-after: 3
    labels:
      - "revert"

# 📝 變更條目格式
change-template: "- $TITLE by $AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&`#@'

# 🏷️ 版本決定邏輯
version-resolver:
  major:
    labels:
      - "breaking"
      - "revert"
  minor:
    labels:
      - "feature"
      - "perf"
      - "security"
      - "refactor"
  patch:
    labels:
      - "bugfix"
      - "style"
      - "unit-test"
      - "documentation"
      - "dependencies"
      - "chore"
  default: patch

# 🎯 自動標籤 (如果 PR 沒有對應標籤)
autolabeler:
  - label: "feature"
    branch:
      - "/^add[/-]/"
      - "/^feat[/-]/"
      - "/^feature[/-]/"

  - label: "bugfix"
    branch:
      - "/^(fix|bug|bugfix|hotfix)[/-]/"

  - label: "breaking"
    branch:
      - "/^breaking[/-]/"
      - "/^major[/-]/"
      - "/^BREAKING[/-]/"

  - label: "perf"
    branch:
      - "/^perf(ormance)?[/-]/"
      - "/^optimize[/-]/"

  - label: "refactor"
    branch:
      - "/^refactor[/-]/"
      - "/^cleanup[/-]/"
      - "/^restructure[/-]/"

  - label: "unit-test"
    branch:
      - "/^tests?[/-]/"

  - label: "documentation"
    branch:
      - "/^docs?[/-]/"
      - "/^documentation[/-]/"

  - label: "style"
    branch:
      - "/^style[/-]/"
      - "/^format[/-]/"
      - "/^lint[/-]/"

  - label: "chore"
    branch:
      - "/^chore[/-]/"
      - "/^maintenance[/-]/"
      - "/^config[/-]/"
      - "/^update[/-]/"

  - label: "dependencies"
    branch:
      - "/^deps?[/-]/"
      - "/^dependabot[/-]/"
      - "/^dependencies[/-]/"

  - label: "security"
    branch:
      - "/^security[/-]/"
      - "/^sec[/-]/"

  - label: "revert"
    branch:
      - "/^revert[/-]/"
      - "/^rollback[/-]/"

# 📄 Release Notes 模板
template: |
  ## 🎉 What's Changed

  $CHANGES

  ---

  ## 📊 Release Statistics

  **Contributors**: $CONTRIBUTORS
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ---

  ## 💡 Need Help?

  - 📖 [Documentation](https://github.com/$OWNER/$REPOSITORY/blob/main/README.md)
  - 🐛 [Report Issues](https://github.com/$OWNER/$REPOSITORY/issues)
  - 💬 [Discussions](https://github.com/$OWNER/$REPOSITORY/discussions)

# 📚 排除的標籤 (不會出現在 release notes 中)
exclude-labels:
  - "skip-changelog"
  - "duplicate"
  - "question"
  - "invalid"
  - "wontfix"
  - "size: xs"
  - "size: small"
  - "size: medium"
  - "size: large"
  - "size: xl"

# 🏷️ 包含的標籤 (只有這些標籤的 PR 會被包含)
include-labels:
  - "breaking"
  - "feature"
  - "bugfix"
  - "perf"
  - "security"
  - "refactor"
  - "style"
  - "unit-test"
  - "documentation"
  - "dependencies"
  - "chore"
  - "revert"
