services:
  tdl_bot:
    image: ghcr.io/mai0313/tdl-bot
    build:
      context: .
      target: prod
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command:
      - python
      - ./bot.py
    restart: always
    pull_policy: always
