services:
  tdl_bot:
    image: ghcr.io/mai0313/tdl-bot
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command:
      - uv
      - run
      - --no-dev
      - --frozen
      - tdl_bot
    restart: always
    pull_policy: always
